#!/bin/bash
#BSUB -J petsc-test
#BSUB -q ser
#BSUB -n 5
#BSUB -W 00:05 
#BSUB -e %J-petsc.err
#BSUB -o %J-petsc.out
#BSUB -m 'r01n12'
module purge
module load intel/2018.4
module load mpi/intel/2018.4

mpirun -np 5 ./hw62.out -ksp_type richardson \
  -ksp_rtol 1.0e-10 \
  -ksp_atol 1.0e-50 -ksp_max_it 1500 \
  -pc_type sor \
  -pc_factor_mat_solver_type mumps \
  -sub_ksp_type richardson \
  -sub_pc_type icc -ksp_monitor_short \
  -ksp_converged_reason \
  -ksp_view \
  -log_view > $LSB_JOBID.log 2>&1
